### ISSUE TITLE
Scroll Problems

### ISSUE THREAD

**Issue by oliveirafilipe** [menosprezzi/material-walkthrough#10]
![12](https://cloud.githubusercontent.com/assets/22033274/18371212/e9cc69ce-7608-11e6-9e4a-53a3ac299863.png)
![whatsapp image 2016-09-08 at 9 10 21 pm](https://cloud.githubusercontent.com/assets/22033274/18371216/f67607e8-7608-11e6-9d67-d1646862ec54.jpeg)

Peguei a aba e deixei ela bem fininha e ele não baixou para centralizar o elemento, assim como num tablet ele não baixou para mostrar e como o scroll ta trancado não tem nada para ser feito... 

Talvez mais testes nos ajudem a solucionar isso

**Comment by menosprezzi** [comment]
Eh, o scrollTo nao ta comprindo o papel dele. Acho que se aplicarmos o scrollTo pra todo resize que for feito isso se solucione.
