### ISSUE TITLE
Phantom scrolls when resize the window (after runs a walkthrough)

### ISSUE THREAD

**Issue by menosprezzi** [menosprezzi/material-walkthrough#15]
Após executar algum walkthrough, a página realiza alguns scrolls sem noção para pontos distintos quando se modifica o tamanho da janela. Isso pode acontecer  pelo fato de que algum listener antigo não foi limpo corretamente.

**Comment by oliveirafilipe** [comment]
Este bug continua MESMO se o walk já acabou '-'

**Comment by menosprezzi** [comment]
Sim. E quanto mais walks são instanciados, maior fica o bug. É algo haver com os eventlisteners de resize.
