### ISSUE TITLE
Stucked scroll in Firefox (linux)

### ISSUE THREAD

**Issue by menosprezzi** [menosprezzi/material-walkthrough#18]
The walk cant scroll the page to locate the target (even up & down). Maybe the scroll blocker's script is causing that issue.

**Comment by menosprezzi** [comment]
It can be an issue caused by the version of jQuery (2.4). We need to replace it to ver. 3

**Comment by oliveirafilipe** [comment]
Same problem in Windows, Firefox v53.0.2 (32-bit)
