### ISSUE TITLE
window.scrollTo Chrome

### ISSUE THREAD

**Issue by oliveirafilipe** [menosprezzi/material-walkthrough#35]
Aparentemente o chrome possui problemas com o `window.scrollTo`, utilizado para centralizarmos o elemento na página.

Issues como [JavaScript issue with scrollTo() in Chrome](https://stackoverflow.com/questions/15691569/javascript-issue-with-scrollto-in-chrome), e [strange behaviour of Chrome at window.scrollTo()](https://stackoverflow.com/questions/15260184/strange-behaviour-of-chrome-at-window-scrollto) mostram que o problema pode ser solucionado com:

`setTimeout(function(){window.scrollTo(0,YCoordinate)}, 500);`

Entretanto isto acaba atrasando em meio segundo a localização do `target`

**Comment by menosprezzi** [comment]
We can dispatch a scroll first to Y: 0 when the plugin loads.
