### ISSUE TITLE
Wrong itCanBeRenderedInBottom

### ISSUE THREAD

**Issue by AirMike** [menosprezzi/material-walkthrough#39]
I think there is a typo which leads to wrong itCanBeRenderedInBottom prediction (v2 branch)

`var itCanBeRenderedInBottom = position.y + MaterialWalkthrough._contentWrapper.offsetHeight + MaterialWalkthrough._contentWrapper.offsetHeight < window.innerHeight;`

There are two MaterialWalkthrough._contentWrapper.offsetHeight where one of them should be MaterialWalkthrough._wrapper.offsetHeight.

**Comment by menosprezzi** [comment]
That's right! I'll gonna fix it now.
<img width="229" alt="screen shot 2018-02-07 at 1 17 06 pm" src="https://user-images.githubusercontent.com/6165501/35924897-763e57d4-0c0b-11e8-92ff-3d1d2f50f96d.png">
Thanks @AirMike.
