### ISSUE TITLE
Change in calculating content position (v2)

### ISSUE THREAD

**Issue by AirMike** [menosprezzi/material-walkthrough#40]
Hi,

can you please change to use position.left instead of position.x and position.top instead of position.y when calculating where content can be positioned.
It will allow support for IE11 which doesn't have support for x,y param but it equals left, top param (in all browsers)

**Comment by oliveirafilipe** [comment]
@AirMike of course. I Will make some tests and update. Thank you

**Comment by oliveirafilipe** [comment]
Closed by 5885285adf82289d47784fd228dccd8f9a808651
