### ISSUE TITLE
Add click handler for the "acceptText" button

### ISSUE THREAD

**Issue by NathanGrimaud** [menosprezzi/material-walkthrough#43]
Hello there ! 
While working with this library, I really missed the ability to register functions that are called when the user is clicking on the "acceptText" button. 
I found a workaround adding an click event on the `walk-action` button, and removing this listener right after the click, but I think that this feature should be built in the library.

**Comment by oliveirafilipe** [comment]
@NathanGrimaud Hello. Thank you for the issue. What version are you using? V1 ([master](https://github.com/essetwide/material-walkthrough)) or V2 ([v2](https://github.com/essetwide/material-walkthrough/tree/v2))? (I advise to use the V2 :smile: )

Talking quickly to @menosprezzi he said: "I think that we already have this custom callback in the button click ". @menosprezzi can you check this again?

**Comment by NathanGrimaud** [comment]
Great news ! I'm using v2 ;) 

After a quick check on the code I found : 

```
* @property {function} [onSet] A function that will be called when the walk content is setted;
* @property {function} [onClose] A function that will be called when the walk is accepted;
```
It's exactly what I wanted, I think that it would be great to add this to the readme .

**Comment by oliveirafilipe** [comment]
@NathanGrimaud Awesome! 

later this month I will do some documentation on the project Wiki. I will close this issue to open one focused on the documentation.

Keep using the plugin and contributing!
