### ISSUE TITLE
Want to know some console.log() value of given code inside MaterialWalkthrough.js

### ISSUE THREAD

**Issue by karanshrm44** [menosprezzi/material-walkthrough#50]
```static _next(){
    const hasNext = !!MaterialWalkthrough._instance.points && !!MaterialWalkthrough._instance.points[MaterialWalkthrough._instance.currentIndex + 1];
      if (hasNext) {
        MaterialWalkthrough._instance.currentIndex++;
        console.log( MaterialWalkthrough._setWalker(
          MaterialWalkthrough._instance.points[MaterialWalkthrough._instance.currentIndex]
        ));
      } else {
        MaterialWalkthrough._instance.currentIndex = 0;
        MaterialWalkthrough._instance.points = null;
        if (MaterialWalkthrough._instance.onCloseCallback) MaterialWalkthrough._instance.onCloseCallback();
        MaterialWalkthrough._instance.onCloseCallback = null;
        MaterialWalkthrough.closeWalker();
      }
  }```

**Comment by oliveirafilipe** [comment]
We will do some refacats in the log process in the v2 branch. What do you want to console in this section? There are some callbacks in the plug-in , we will refact the docs to for the v2 release

**Comment by karanshrm44** [comment]
I just want to see what is the value of  this particular method ?? How it is working?

**Comment by oliveirafilipe** [comment]
Hi @karanshrm44, first wich version are you using? 

So do you want to know the return value of the `setWalker` method?

The `setWalker` its a `void` method, it runs every position in the walkpoints array (passed as parameter), and do all the magic. Basically, it locates the target and render the wrapper

**Comment by karanshrm44** [comment]
I am using version v2, pure vanilla, I want to know how can i run your code locally

**Comment by oliveirafilipe** [comment]
Now i see what you want. The project uses rollup pkg because we are using ES6 with Import sintax inside the `/src` folder. 

In order to run your code in the browser and see some change, you need first to do your changes under the `/src` folder then run `npm run build` to transpile the code, that will be generated under `/dist` folder.

it's worth pointing out that you need to follow the [NPM workflow](https://docs.npmjs.com/getting-started/installing-npm-packages-locally)

**Comment by karanshrm44** [comment]
How can I contact personally gitter or similar like that ? I have few more question to ask @oliveirafilipe

**Comment by oliveirafilipe** [comment]
@karanshrm44 https://tlk.io/material-walkthrough
