### ISSUE TITLE
How to Create a Walkthrough

### ISSUE THREAD

**Issue by oliveirafilipe** [menosprezzi/material-walkthrough#7]
$.walk(["ARRAY CONTENTO IDS DOS OBJETIVOS"], {
 walkForm: 'circ' OR 'rect',
 color: {  NOME DO ID 1: red,
            NOME_ID_2:blue
},
mais definicoes,
mais definicoes
});

**Comment by menosprezzi** [comment]
```
$.walk([{
id: ID_OBJETO1,
color: COR_DO_FUNDO1,
type: circle/rect,
text: TEXTO_CONTEUDO1
}, 
{id: ID_OBJETO2,
color: COR_DO_FUNDO2,
type: circle/rect,
text: TEXTO_CONTEUDO2
} ...]);
```

**Comment by karanshrm44** [comment]
I am using this thing in react project but it is not working ??

**Comment by oliveirafilipe** [comment]
@karanshrm44 what version are you using? Did you follow the read me instructions?

**Comment by menosprezzi** [comment]
@karanshrm44 To achieve a better compatibility with React, I advise you to use the `v2` branch, that's use vanilla JS, with no dependencies with Jquery.

Following your other comments here in the repo, I'm realizing that you're trying to code with the v2 of this package reading the v1 documentation...
Follow the v2 (README)[https://github.com/essetwide/material-walkthrough/tree/v2] from zero and I believe that you can work with it.
